### ISSUE TITLE
Create Components for Status Buttons

### ISSUE THREAD

**Issue by andytudhope** [status-im/storybook#3]
We are in the process of moving some of our design work from Figma to react-storybooks so that it is:

1. Easier for developers to work quickly and iterate
2. Easier for designers and developers to work in tandem and provide functional feedback on each other's requirements and proposals.
3. We can continue moving toward a more standard library of components that can be used across Status, as well as by the wider community of DApp developers.

The third components we'd like built are the Buttons (and Button cells) [here](https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=0%3A1).

There will be a bounty for the issue after a little more discussion/clarification.

**Comment by bgits** [comment]
I have created the desktop button as per the Desktop designs for the voting dapp, but looking at these designs I don't see that button. 

https://status-im.github.io/storybook/?knob-Text=Your%20text%20here&knob-active=true&knob-Styles=%7B%7D&selectedKind=DesktopButton&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by bgits** [comment]
Added the below four buttons, was able to generalize them into one component - see Button > Select Type - in Storybook, and you can toggle them by selecting the `Button Type` under `Knobs`

<img width="805" alt="screen shot 2018-10-12 at 4 36 00 pm" src="https://user-images.githubusercontent.com/4020296/46892881-f34bf080-ce3c-11e8-9ee3-5867272040e5.png">

https://status-im.github.io/storybook/?knob-Text=Label&knob-Styles=%7B%7D&knob-Button%20Type=primary&selectedKind=Button&selectedStory=Select%20Type&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by bgits** [comment]
@andytudhope I guess we can close this out as well it's effectively done.

**Comment by denis-sharypin** [comment]
@bgits unfortunately, the implemented button doesn't match the one from the library. Wrong letters case, paddings between arrow and button label. And we should talk about the font that we are going to use there
